### ISSUE TITLE
New method in l7

### ISSUE THREAD

**Issue by Xoosz** [SkyWtkh/Stellar#1]
bro MHDDoS Layer7 method put here in the panel for more methods

**Comment by SkyWtkh** [comment]
In v2 you will see some MH methods!

**Comment by Xoosz** [comment]
okay, the design of your ddos panel is the same as zentle

**Comment by Xoosz** [comment]
it's better if you imitate the design to resemble then all the methods in mhddos put on your panel

**Comment by Xoosz** [comment]
gl
