### ISSUE TITLE
Telnet Not Working

### ISSUE THREAD

**Issue by FranklinOP-IND** [SkyWtkh/Stellar#2]
Usage: telnet <ip> <threads> <pps> <time>
┌──(@root)-[/r00t/stellar/]
└─> telnet 139.99.XX.X0 9999 44 500
sudo: ./telnet: command not found

LAYER 4 Not Working any

**Comment by SkyWtkh** [comment]
Before starting Stellar run the command: chmod +x *
there if I would have to let you execute the methods for layer 4

**Comment by FranklinOP-IND** [comment]
> Before starting Stellar run the command: chmod +x * there if I would have to let you execute the methods for layer 4

Any Have Another Pannel Like Down Server Proxy Bypass (Some Server Using Proxys Layer How can I down Them I Have 25GGEs internet 36 Core Vps)

**Comment by FranklinOP-IND** [comment]
Working Good 
![image](https://user-images.githubusercontent.com/64591314/158018234-3bfc480d-0dcc-4e5f-821d-4e7f067d8e97.png)
![image](https://user-images.githubusercontent.com/64591314/158018244-95ade19a-ada8-41a9-ada5-7e2d7872ca77.png)

**Comment by FranklinOP-IND** [comment]
Change This One
![image](https://user-images.githubusercontent.com/64591314/158018362-29033def-a2bf-4300-a391-e7dba87addb7.png)
cd Stellar-New-Age

**Comment by SkyWtkh** [comment]
Thanks for telling me that mistake! (cd RayNet) and also thanks for occupying Stellar!
