### ISSUE TITLE
I love you

### ISSUE THREAD

**Issue by M1R1ZAL1** [SkyWtkh/Stellar#3]
how can I contact you? and when i want to attack i get rpc error how do my for fix error

**Comment by SkyWtkh** [comment]
send capture or tell me the error here ( github issues )

**Comment by M1R1ZAL1** [comment]
I did it dude, but why doesn't goat-bypass bypass captcha? and are there any other scripts layer 7

**Comment by SkyWtkh** [comment]
the bypass "goat" does not bypass captcha (or maybe it does but it is not frequent) and yes, there are more methods for layer 7

**Comment by M1R1ZAL1** [comment]
when will new methods come, or when will stellar v2 come? I want to communicate with you.

**Comment by M1R1ZAL1** [comment]
and i get http-root error, can i know why?

**Comment by SkyWtkh** [comment]
Version 2 already has new methods (right now I'm developing v3), could you tell me the error that http-root gives you?

**Comment by M1R1ZAL1** [comment]
of course i can show the error and where can i find version 2 and when will version 3 end

**Comment by M1R1ZAL1** [comment]
![Uploading IMG_20220312_204219_991.jpg…]()

**Comment by SkyWtkh** [comment]
It won't let me see the picture...
and yesterday I uploaded v2 to github to this same repository (github.com/SkyWtkh/Stellar-New-Age)

**Comment by M1R1ZAL1** [comment]
![IMG_20220312_204219_991](https://user-images.githubusercontent.com/98713098/158029114-f141fecd-98ac-4fe4-978d-a1c13baa359f.jpg)

**Comment by SkyWtkh** [comment]
http-root is only for HTTP not for HTTPS

**Comment by M1R1ZAL1** [comment]
okey thank you

**Comment by M1R1ZAL1** [comment]
when will version 3 end

**Comment by SkyWtkh** [comment]
Tomorrow version 3 will be released in this same repository

**Comment by M1R1ZAL1** [comment]
okey thank you ❤

**Comment by M1R1ZAL1** [comment]
where can i contact you and will there be new layer 7 methods which protections will be bypassed

**Comment by SkyWtkh** [comment]
1: I withdraw what I said that v3 will come out tomorrow since in 1 hour or less it will come out
2: I'm sorry but I don't pass my contact (discord / telegram) to people on the internet that I don't know but you can talk to me here (github issues)
3: for v3 there will be 3 new bypasses and for v4 5 bypasses

**Comment by M1R1ZAL1** [comment]
so v3 will be released in 1 hour?

**Comment by SkyWtkh** [comment]
version 3 is here! you can clone/download this repository and try the new version

**Comment by M1R1ZAL1** [comment]
omg this is awsome ! version 3 how do i download

**Comment by M1R1ZAL1** [comment]
![20220313_020246](https://user-images.githubusercontent.com/98713098/158038018-caba9ff9-cd5d-4ef0-9783-ae39bac9bf5b.jpg)

**Comment by M1R1ZAL1** [comment]
wtf xD

**Comment by SkyWtkh** [comment]
That's because your terminal doesn't accept x1b to colorize your terminal.

**Comment by M1R1ZAL1** [comment]
how do i color it and accept x1b

**Comment by M1R1ZAL1** [comment]
Does the new script definitely skip hcaptcha?

**Comment by M1R1ZAL1** [comment]
and share new file don't update files

**Comment by SkyWtkh** [comment]
hcaptcha-solver only solve captcha and show the response, it is not a flood

**Comment by M1R1ZAL1** [comment]
What does captcha-resolver scan for

**Comment by SkyWtkh** [comment]
solve hcaptcha xd, the truth is I don't know why I put that method

**Comment by M1R1ZAL1** [comment]
xd

**Comment by M1R1ZAL1** [comment]
![IMG_20220313_214343_326](https://user-images.githubusercontent.com/98713098/158074418-1ff53e05-9091-415c-965b-6312ddd453b7.jpg)

**Comment by M1R1ZAL1** [comment]
when will version 4 end xD

**Comment by SkyWtkh** [comment]
Maybe in 4 days or less, idk...

**Comment by M1R1ZAL1** [comment]
ok thanks

**Comment by M1R1ZAL1** [comment]
![IMG_20220313_214343_326](https://user-images.githubusercontent.com/98713098/158079960-03a82414-63ce-4df6-82c9-04dadf0ef1a4.jpg)

**Comment by M1R1ZAL1** [comment]
can you help me?

**Comment by SkyWtkh** [comment]
I can't bypass the captcha that's the problem

**Comment by M1R1ZAL1** [comment]
huh?

**Comment by SkyWtkh** [comment]
I did not understand your question

**Comment by M1R1ZAL1** [comment]
can i skip hcaptcha in v4

**Comment by SkyWtkh** [comment]
no

**Comment by M1R1ZAL1** [comment]
:/ ok
