### ISSUE TITLE
MH-pps 

### ISSUE THREAD

**Issue by FranklinOP-IND** [SkyWtkh/Stellar#5]
![image](https://user-images.githubusercontent.com/64591314/158025124-cd9eba58-d39e-4acd-be65-d9f6f5a349fe.png)

**Comment by M1R1ZAL1** [comment]
mh-pps , get and mh cloudflare are very bad methods I suggest you to use cf-bypass and goat bypass.

**Comment by SkyWtkh** [comment]
W, only methods like MH-GET or MH-POST are half good, now, with the franklin error it has never happened to me (not even in google cloud shell, any linux distro, etc) so I don't know how to help you :( these are my recommendations: lower the number of threads, look for the error on the internet or run a new terminal as ROOT user

**Comment by FranklinOP-IND** [comment]
> W, only methods like MH-GET or MH-POST are half good, now, with the franklin error it has never happened to me (not even in google cloud shell, any linux distro, etc) so I don't know how to help you :( these are my recommendations: lower the number of threads, look for the error on the internet or run a new terminal as ROOT user

yup found them(pps lower 100) but all use them Good Is goat-bypass
