### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Xoosz** [SkyWtkh/Stellar#6]
Goat-bypass no effect

**Comment by SkyWtkh** [comment]
Goat-Bypass is fairly old so it won't work in all cases, at least once goat-bypass worked for me against a DDoS-Guard protected page

**Comment by Xoosz** [comment]
But when the target is on UAM, Goat-Bypass does not work

**Comment by SkyWtkh** [comment]
Sorry :(, For v4 I will try to find a new bypass for CF UAM

**Comment by Xoosz** [comment]
you can get free scripts here https://github.com/R00tS3c/DDOS-RootSec

**Comment by SkyWtkh** [comment]
Thx bro!

**Comment by Xoosz** [comment]
No problem, im waiting V4😉

**Comment by Xoosz** [comment]
keep updating this panel, it will soon become our botnet

**Comment by SkyWtkh** [comment]
Some day...
