### ISSUE TITLE
Request for the panel pls read

### ISSUE THREAD

**Issue by pl8g** [SkyWtkh/Stellar#7]
Hey man. 
Awesome panel good methods everything about this panel is just awesome. 
Can you please add some bots so it can be a botnet? 
Or just make it a botnet and we add our own bots. 
ty :)

**Comment by SkyWtkh** [comment]
this panel occupies http proxies for attacks in a distributed way, not electric microwaves infected with a botnet
but thanks for the idea! Someday I'll try to create a botnet or something and publish it on my github but that will be a long time...

**Comment by pl8g** [comment]
Thanks for explanation :)
Looking forward to the v4 :))))))) 
Keep going man best panel I seen.

**Comment by SkyWtkh** [comment]
People like you make me want to keep updating Stellar.
Thanks for the support!

**Comment by 38Ja** [comment]
cant wait for V4, maybe in future add l4 spoofed. Best panel and keep going.

**Comment by SkyWtkh** [comment]
I think I have a method for l4 spoofed, I'll add it!
